basic/models/Category.php
<?php

namespace app\models;
use yii\db\ActiveRecord;

class Category extends ActiveRecord{
    
    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }
    
    public static function tableName() {
        return 'category';
    }
    
    public function getProducts(){
        return $this->hasMany(Product::className(), ['category_id' => 'id']);
    }
}

basic/controllers/CartController.php
<?php

namespace app\controllers;
use app\models\Product;
use app\models\Cart;
use app\models\Order;
use app\models\OrderItems;
use Yii;

class CartController extends AppController{
    //Добавление товара в корзину Ajax запросом
    public function actionAdd(){
        //получение id товара добавляемого в корзину
        $id = Yii::$app->request->get('id');
        //получение количества товара и приведение к целому числу
        $qty = (int)Yii::$app->request->get('qty');
        //Если qty не число, в корзину добавляется 1 товар,
        // иначе количество qty
        $qty = !$qty ? 1 : $qty;
        
        //запрос к БД
        $product = Product::findOne($id);
        //если запрос ничего не вернул
        if(empty($product)){
            return FALSE;
        }
        //откытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //модель
        $cart = new Cart();
        $cart->addToCart($product, $qty);
        
        //Добавление в корзину в случае отключения javascript
        if (!Yii::$app->request->isAjax){
            return $this->redirect(Yii::$app->request->referrer);
        }
        
        //отключение шаблона
        $this->layout = FALSE;
        
        return $this->render('cart-modal', compact('session'));
    }
    //Очистка корзины
    public function actionClear(){
        //открытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //удаление из сессии всех данных о товарах
        $session->remove('cart');
        $session->remove('cart.qty');
        $session->remove('cart.sum');
        
        //отключение шаблона
        $this->layout = FALSE;
        
        return $this->render('cart-modal', compact('session'));
    }
    
    //Удаление одного товара из корзины при нажатии на крестик
    public function actionDelItem(){
        //получение id товара удаляемого из корзины
        $id = Yii::$app->request->get('id');
        
        //открытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //Подключение модели
        $cart = new Cart();
        $cart->recalc($id);
        
        //отключение шаблона
        $this->layout = FALSE;
        
        return $this->render('cart-modal', compact('session'));
    }
    
    //Открытие корзины при нажатии на значек в Header
    public function actionShow(){
        
        //открытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //отключение шаблона
        $this->layout = FALSE;
        
        return $this->render('cart-modal', compact('session'));
    }
    //Обработка заказа
    public function actionView(){
        //открытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //Установка заголовка для страницы
        $this->setMeta('Корзина');
        
        //Подключение модели
        $order = new Order();
        
        if($order->load(Yii::$app->request->post())){
            $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];
            
            if($order->save()){
                $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success', 'Ваш заказ принят.');
                
                //отправка письма заказа
                Yii::$app->mailer->compose('order', ['session' => $session])
                        ->setFrom(['test@mail.ru' => 'shop2'])
                        ->setTo($order->email)
                        ->setSubject('Заказ')
                        ->send();
                
                //очистка корзины
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                        
                return $this->refresh();
            }else{
                Yii::$app->session->setFlash('error', 'Ошибка оформления заказа!');
            }
        }
        
        return $this->render('view', compact('session', 'order'));
    }
    
    //Сохранение заказанных товаров в таблицу order_items
    protected function saveOrderItems($items, $order_id){
        foreach($items as $id => $item){
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty'] * $item['price'];
            $order_items->save();
        }
    }
}

basic/controllers/CategoryController.php
<?php

namespace app\controllers;
use app\models\Category;
use app\models\Product;
use yii\data\Pagination;
use yii\web\HttpException;
use Yii;

class CategoryController extends AppController {
    
    public function actionIndex(){
        //Запрос к БД для Популярные товары
        $hits = Product::find()->where(['hit' => '1'])->limit(9)->all();
        $this->setMeta('Тестовый магазин на Yii2');
        return $this->render('index', compact('hits'));
    }
    
    public function actionView($id){
//        $id = Yii::$app->request->get('id');
        //Запрос на категорию по id
        $category = Category::findOne($id);
        //В случае, если такой категории нет выводится страница с ошибкой
        if(empty($category)){
            throw new HttpException(404, 'Что-то пошло не так и мы не смогли найти нужную категорию');
        }
        
//        $products = Product::find()->where(['category_id' => $id])->all();
        //Включение пагинации для товаров по категориям
        $query = Product::find()->where(['category_id' => $id]);
        $pages = new Pagination(['totalCount' => $query->count(),
            'pageSize' => 3, 'forcePageParam' => FALSE, 'pageSizeParam' => FALSE]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        
        //Установка метатегов
        $this->setMeta('Тестовый магазин на Yii2 | ' . $category->name, $category->keywords,
                $category->description);
        
        return $this->render('view', compact('products', 'pages', 'category'));
    }
    
    public function actionSearch(){
        //получение поискового запроса с учетом пробелов
        $q = trim(Yii::$app->request->get('q'));
        
        //Установка метатегов
        $this->setMeta('Тестовый магазин на Yii2 | Поиск: ' . $q);
        
        //обработка поиска в случае, если строка поиска пустая
        if(!$q){
            return $this->render('search');
        }
        //Включение пагинации для товаров по категориям из поискового запроса
        $query = Product::find()->where(['like', 'name', $q]);
        
        $pages = new Pagination(['totalCount' => $query->count(),
            'pageSize' => 3, 'forcePageParam' => FALSE, 'pageSizeParam' => FALSE]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        
        return $this->render('search', compact('products', 'pages', 'q'));
    }
}

basic/controllers/ProductController.php
<?php

namespace app\controllers;
use app\models\Category;
use app\models\Product;
use Yii;
use yii\web\HttpException;

class ProductController extends AppController {
    
    public function actionView($id){
        //Получение id товара через Get запрос
//        $id = Yii::$app->request->get('id');
        //Ленивая загрузка данных товара по id из БД
        $product =  Product::findOne($id);
        //В случае, если такого товара нет, выводится страница с ошибкой
        if(empty($product)){
            throw new HttpException(404, 'Что-то пошло не так и страница с товаром не была найдена');
        }
        
        //Жадная загрузка
//        $product = Product::find()->with('category')->where(['id' => $id])->limit(1)->one();
        //Запрос к БД для Популярные товары
        $hits = Product::find()->where(['hit' => '1'])->limit(9)->all();
        //Установка метатегов
        $this->setMeta('Тестовый магазин на Yii2 | ' . $product->name, $product->keywords,
                $product->description);
        
        return $this->render('view', compact('product', 'hits'));
    }
}

basic/views/category/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
/* @var $this yii\web\View */

//$this->title = 'My Yii Application';
?>
<!--	<section id="slider">slider
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>
						
						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Free E-Commerce Template</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="images/home/girl1.jpg" class="girl img-responsive" alt="" />
									<img src="images/home/pricing.png"  class="pricing" alt="" />
								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>100% Responsive Design</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="images/home/girl2.jpg" class="girl img-responsive" alt="" />
									<img src="images/home/pricing.png"  class="pricing" alt="" />
								</div>
							</div>
							
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Free Ecommerce Template</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="images/home/girl3.jpg" class="girl img-responsive" alt="" />
									<img src="images/home/pricing.png" class="pricing" alt="" />
								</div>
							</div>
							
						</div>
						
						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>
					
				</div>
			</div>
		</div>
	</section>/slider-->
	
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3"><!--Левое меню категорий-->
					<div class="left-sidebar">
						<h2>Категории</h2>
                                                
                                                <ul class="catalog category-products">
                                                <?= \app\components\MenuWidget::Widget(['tpl' => 'menu']); ?>
                                                </ul>
					</div>
				</div><!--/Левое меню категорий-->
				
				<div class="col-sm-9 padding-right">
                                    <?php if(!empty($hits)): ?><div class="features_items"><!--features_items-->
                                            <h2 class="title text-center">Популярные товары</h2>
                                                <?php foreach($hits as $hit): ?>
                                                    <div class="col-sm-4">
                                                        <div class="product-image-wrapper">
                                                            <div class="single-products">
                                                                <div class="productinfo text-center">
                                                                    <a href="<?= Url::to(['product/view', 'id' => $hit->id]) ?>">
                                                                        <?php $mainImage = $hit->getImage();?>
                                                                        <?= Html::img($mainImage->getUrl(), ['alt' => $hit->name]); ?>
                                                                    </a>
                                                                    <h2>&#8381;<?= $hit->price?></h2>
                                                                    <p><a href="<?= Url::to(['product/view', 'id' => $hit->id]) ?>"><?= $hit->name?></a></p>
                                                                    <a href="<?= Url::to(['cart/add', 'id' => $hit->id]) ?>" data-id="<?= $hit->id?>" class="btn btn-default add-to-cart">
                                                                        <i class="fa fa-shopping-cart"></i>В корзину
                                                                    </a>
                                                                </div>
                                                                    <?php if($hit->new): ?>
                                                                    <?= Html::img("@web/images/home/new.png", ['alt' => 'Новинка', 'class' => 'new']); ?>
                                                                    <?php endif; ?>
                                                                    <?php if($hit->sale): ?>
                                                                    <?= Html::img("@web/images/home/sale.png", ['alt' => 'Распродажа', 'class' => 'new']); ?>
                                                                    <?php endif; ?>
                                                            </div>
                                                        </div>
                                                    </div>
                                            <?php endforeach; ?>
                                        </div><!--/features_items-->
                                    <?php endif; ?>
				</div>
			</div>
		</div>
	</section>

basic/views/category/search.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
/* @var $this yii\web\View */

//$this->title = 'My Yii Application';
?>	
<!--<section id="advertisement">
		<div class="container">
			<img src="/images/shop/advertisement.jpg" alt="" />
		</div>
</section>-->
	
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Категории</h2>
						
                                                <ul class="catalog category-products"><!--Левое меню категорий-->
                                                <?= \app\components\MenuWidget::Widget(['tpl' => 'menu']); ?>
                                                </ul><!--/Левое меню категорий-->
					
<!--						<div class="brands_products">brands_products
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
									<li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
									<li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
									<li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
									<li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
									<li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
									<li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
								</ul>
							</div>
						</div>/brands_products
						
						<div class="price-range">price-range
							<h2>Price Range</h2>
							<div class="well">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b>$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div>/price-range
						
						<div class="shipping text-center">shipping
							<img src="/images/home/shipping.jpg" alt="" />
						</div>/shipping-->
						
					</div>
				</div>
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
                                            <h2 class="title text-center">Поиск по запросу: <?= Html::encode($q); ?></h2>
                                                <?php if(!empty($products)): ?>
                                                <?php $i = 0; foreach ($products as $product): ?>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
                                                                            <a href="<?= Url::to(['product/view', 'id' => $product->id]) ?>">
										<?php $mainImage = $product->getImage();?>
                                                                        <?= Html::img($mainImage->getUrl(), ['alt' => $product->name]); ?>
                                                                            </a>
										<h2>&#8381;<?= $product->price ?></h2>
                                                                                <p><a href="<?= Url::to(['product/view', 'id' => $product->id]) ?>"><?= $product->name ?></a></p>
										<a href="#" data-id="<?= $product->id ?>" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
									</div>
                                                                        <?php if($product->new): ?>
<!--                                                                    <img src="images/home/new.png" class="new" alt="" />-->
                                                                        <?= Html::img("@web/images/home/new.png", ['alt' => 'Новинка', 'class' => 'new']); ?>
                                                                        <?php endif; ?>
                                                                        <?php if($product->sale): ?>
    <!--                                                                <img src="images/home/sale.png" class="new" alt="" />-->
                                                                        <?= Html::img("@web/images/home/sale.png", ['alt' => 'Распродажа', 'class' => 'new']); ?>
                                                                        <?php endif; ?>
								</div>
<!--								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
									</ul>
								</div>-->
							</div>
						</div>
                                                <?php $i++; ?>
                                                <?php if($i % 3 == 0 ): ?>
                                                <div class="clearfix"></div>
                                                <?php endif; ?>
                                                <?php endforeach; ?>
                                                <!--Сброс обтекания-->
						<div class="clearfix"></div>
                                                <!--Вывод пагинации-->
                                                <?php
                                                    echo \yii\widgets\LinkPager::widget([
                                                       'pagination' => $pages, 
                                                    ]);?>
                                                <!--/Вывод пагинации-->
                                                <?php else: ?>
                                                <h2>Ничего не найдено</h2>
						<?php endif; ?>
                                                <!--Сброс обтекания-->
						<div class="clearfix"></div>
					</div><!--features_items-->
				</div>
			</div>
		</div>
	</section>

basic/views/category/view.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
/* @var $this yii\web\View */

//$this->title = 'My Yii Application';
?>	
<!--<section id="advertisement">
		<div class="container">
			<img src="/images/shop/advertisement.jpg" alt="" />
		</div>
	</section>-->
	
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Категории</h2>
						
                                                <ul class="catalog category-products"><!--Левое меню категорий-->
                                                <?= \app\components\MenuWidget::Widget(['tpl' => 'menu']); ?>
                                                </ul><!--/Левое меню категорий-->
					
<!--						<div class="brands_products">brands_products
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
									<li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
									<li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
									<li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
									<li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
									<li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
									<li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
								</ul>
							</div>
						</div>/brands_products
						
						<div class="price-range">price-range
							<h2>Price Range</h2>
							<div class="well">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b>$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div>/price-range
						
						<div class="shipping text-center">shipping
							<img src="/images/home/shipping.jpg" alt="" />
						</div>/shipping-->
						
					</div>
				</div>
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center"><?= $category->name ?></h2>
                                                <?php if(!empty($products)): ?>
                                                <?php $i = 0; foreach ($products as $product): ?>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
                                                                            <a href="<?= Url::to(['product/view', 'id' => $product->id]) ?>">
										<?php $mainImage = $product->getImage();?>
                                                                        <?= Html::img($mainImage->getUrl(), ['alt' => $product->name]); ?>
                                                                            </a>
										<h2>&#8381;<?= $product->price ?></h2>
                                                                                <p><a href="<?= Url::to(['product/view', 'id' => $product->id]) ?>"><?= $product->name ?></a></p>
										<a href="#" data-id="<?= $product->id ?>" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Добавить в корзину</a>
									</div>
<!--									<div class="product-overlay">
										<div class="overlay-content">
											<h2>$<?= $product->price ?></h2>
											<p><?= $product->name ?></p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div>-->
                                                                        <?php if($product->new): ?>
<!--                                                                    <img src="images/home/new.png" class="new" alt="" />-->
                                                                        <?= Html::img("@web/images/home/new.png", ['alt' => 'Новинка', 'class' => 'new']); ?>
                                                                        <?php endif; ?>
                                                                        <?php if($product->sale): ?>
    <!--                                                                <img src="images/home/sale.png" class="new" alt="" />-->
                                                                        <?= Html::img("@web/images/home/sale.png", ['alt' => 'Распродажа', 'class' => 'new']); ?>
                                                                        <?php endif; ?>
								</div>
<!--								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
									</ul>
								</div>-->
							</div>
						</div>
                                                <?php $i++; ?>
                                                <?php if($i % 3 == 0 ): ?>
                                                <div class="clearfix"></div>
                                                <?php endif; ?>
                                                <?php endforeach; ?>
                                                <!--Сброс обтекания-->
						<div class="clearfix"></div>
                                                <!--Вывод пагинации-->
                                                <?php
                                                    echo \yii\widgets\LinkPager::widget([
                                                       'pagination' => $pages, 
                                                    ]);?>
                                                <!--/Вывод пагинации-->
                                                <?php else: ?>
                                                <h2>В этой категории товаров пока нет</h2>
						<?php endif; ?>
                                                <!--Сброс обтекания-->
						<div class="clearfix"></div>
                                                
<!--						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>-->
					</div><!--features_items-->
				</div>
			</div>
		</div>
	</section>