basic/controllers/CartController.php
<?php

namespace app\controllers;
use app\models\Product;
use app\models\Cart;
use app\models\Order;
use app\models\OrderItems;
use Yii;

class CartController extends AppController{
    //Добавление товара в корзину Ajax запросом
    public function actionAdd(){
        //получение id товара добавляемого в корзину
        $id = Yii::$app->request->get('id');
        //получение количества товара и приведение к целому числу
        $qty = (int)Yii::$app->request->get('qty');
        //Если qty не число, в корзину добавляется 1 товар,
        // иначе количество qty
        $qty = !$qty ? 1 : $qty;
        
        //запрос к БД
        $product = Product::findOne($id);
        //если запрос ничего не вернул
        if(empty($product)){
            return FALSE;
        }
        //откытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //модель
        $cart = new Cart();
        $cart->addToCart($product, $qty);
        
        //Добавление в корзину в случае отключения javascript
        if (!Yii::$app->request->isAjax){
            return $this->redirect(Yii::$app->request->referrer);
        }
        
        //отключение шаблона
        $this->layout = FALSE;
        
        return $this->render('cart-modal', compact('session'));
    }
    //Очистка корзины
    public function actionClear(){
        //открытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //удаление из сессии всех данных о товарах
        $session->remove('cart');
        $session->remove('cart.qty');
        $session->remove('cart.sum');
        
        //отключение шаблона
        $this->layout = FALSE;
        
        return $this->render('cart-modal', compact('session'));
    }
    
    //Удаление одного товара из корзины при нажатии на крестик
    public function actionDelItem(){
        //получение id товара удаляемого из корзины
        $id = Yii::$app->request->get('id');
        
        //открытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //Подключение модели
        $cart = new Cart();
        $cart->recalc($id);
        
        //отключение шаблона
        $this->layout = FALSE;
        
        return $this->render('cart-modal', compact('session'));
    }
    
    //Открытие корзины при нажатии на значек в Header
    public function actionShow(){
        
        //открытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //отключение шаблона
        $this->layout = FALSE;
        
        return $this->render('cart-modal', compact('session'));
    }
    //Обработка заказа
    public function actionView(){
        //открытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //Установка заголовка для страницы
        $this->setMeta('Корзина');
        
        //Подключение модели
        $order = new Order();
        
        if($order->load(Yii::$app->request->post())){
            $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];
            
            if($order->save()){
                $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success', 'Ваш заказ принят.');
                
                //отправка письма заказа
                Yii::$app->mailer->compose('order', ['session' => $session])
                        ->setFrom(['test@mail.ru' => 'shop2'])
                        ->setTo($order->email)
                        ->setSubject('Заказ')
                        ->send();
                
                //очистка корзины
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                        
                return $this->refresh();
            }else{
                Yii::$app->session->setFlash('error', 'Ошибка оформления заказа!');
            }
        }
        
        return $this->render('view', compact('session', 'order'));
    }
    
    //Сохранение заказанных товаров в таблицу order_items
    protected function saveOrderItems($items, $order_id){
        foreach($items as $id => $item){
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty'] * $item['price'];
            $order_items->save();
        }
    }
}

basic/controllers/CategoryController.php
<?php

namespace app\controllers;
use app\models\Category;
use app\models\Product;
use yii\data\Pagination;
use yii\web\HttpException;
use Yii;

class CategoryController extends AppController {
    
    public function actionIndex(){
        //Запрос к БД для Популярные товары
        $hits = Product::find()->where(['hit' => '1'])->limit(9)->all();
        $this->setMeta('Тестовый магазин на Yii2');
        return $this->render('index', compact('hits'));
    }
    
    public function actionView($id){
//        $id = Yii::$app->request->get('id');
        //Запрос на категорию по id
        $category = Category::findOne($id);
        //В случае, если такой категории нет выводится страница с ошибкой
        if(empty($category)){
            throw new HttpException(404, 'Что-то пошло не так и мы не смогли найти нужную категорию');
        }
        
//        $products = Product::find()->where(['category_id' => $id])->all();
        //Включение пагинации для товаров по категориям
        $query = Product::find()->where(['category_id' => $id]);
        $pages = new Pagination(['totalCount' => $query->count(),
            'pageSize' => 3, 'forcePageParam' => FALSE, 'pageSizeParam' => FALSE]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        
        //Установка метатегов
        $this->setMeta('Тестовый магазин на Yii2 | ' . $category->name, $category->keywords,
                $category->description);
        
        return $this->render('view', compact('products', 'pages', 'category'));
    }
    
    public function actionSearch(){
        //получение поискового запроса с учетом пробелов
        $q = trim(Yii::$app->request->get('q'));
        
        //Установка метатегов
        $this->setMeta('Тестовый магазин на Yii2 | Поиск: ' . $q);
        
        //обработка поиска в случае, если строка поиска пустая
        if(!$q){
            return $this->render('search');
        }
        //Включение пагинации для товаров по категориям из поискового запроса
        $query = Product::find()->where(['like', 'name', $q]);
        
        $pages = new Pagination(['totalCount' => $query->count(),
            'pageSize' => 3, 'forcePageParam' => FALSE, 'pageSizeParam' => FALSE]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        
        return $this->render('search', compact('products', 'pages', 'q'));
    }
}

basic/views/layouts/_main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

basic/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;
use app\assets\AppAsset;
use app\assets\ltAppAsset;
use yii\bootstrap\Modal;

AppAsset::register($this);
ltAppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?> 
    <link rel="shortcut icon" href="/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
<?php $this->beginBody() ?>
	<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +7 925 024 57 09</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> makeitpossible@yandex.ru</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
                                                    <a href="<?= Url::home()?>"><?= Html::img('@web/images/logo/yii_small_logo.png', ['alt' => 'Тестовый магазин на Yii2']) ?></a>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
                                                                <?php if (!Yii::$app->user->isGuest): ?>
								<li>
                                                                    <a href="<?= Url::to(['/site/logout']) ?>">
                                                                        <i class="fa fa-user"></i> <?= Yii::$app->user->identity['username'] ?> (Выход)
                                                                    </a>
                                                                </li>
                                                                <?php endif; ?>
                                                                <li><a href="#" onclick="return getCart();"><i class="fa fa-shopping-cart"></i> Корзина</a></li>
                                                                
                                                                <?php if (!Yii::$app->user->isGuest): ?>
                                                                <li><a href="<?= Url::to(['/admin/order']) ?>"><i class="fa fa-lock"></i> Админка</a></li>
                                                                <?php else: ?>
                                                                <li>
                                                                    <a href="<?= Url::to(['/admin'])?>">
                                                                        <i class="fa fa-lock"></i> Вход
                                                                    </a>
                                                                </li>
                                                                <?php endif; ?>
                                                                
                                                                
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="<?= Url::home()?>" class="active">Главная</a></li>
								<li class="dropdown"><a href="#">Магазин<i class="fa fa-angle-down"></i></a>
                                                        <ul role="menu" class="sub-menu">
                                                                <li><a href="#" onclick="return getCart();"><i class="fa fa-shopping-cart"></i> Корзина</a></li>
                                                                <?php if (!Yii::$app->user->isGuest): ?>
                                                                <li><a href="<?= Url::to(['/admin/order']) ?>"><i class="fa fa-lock"></i> Админка</a></li>
                                                                <?php else: ?>
                                                                <li>
                                                                    <a href="<?= Url::to(['/admin'])?>">
                                                                        <i class="fa fa-lock"></i> Вход
                                                                    </a>
                                                                </li>
                                                                <?php endif; ?>
                                                         </ul>
                                </li> 
								<li class="dropdown"><a href="#">Исходники<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="https://gitlab.com/Rafail/shop2-yii2.git">Gitlab</a></li>
                                    </ul>
                                </li> 
<!--								<li><a href="404.html">404</a></li>-->
<!--								<li><a href="contact-us.html">Контакты</a></li>-->
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right">
                                                    <form method="get" id="search" action="<?= Url::to(['category/search']) ?>">
                                                        <input type="text" placeholder="Поиск" name="q">
                                                    </form>
                                                    
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->
	
<?php echo $content; ?>
	
	<footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>e</span>-shopper</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="/images/home/iframe1.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="/images/home/iframe2.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="/images/home/iframe3.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="/images/home/iframe4.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="/images/home/map.png" alt="" />
							<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<li><a href="#">Change Location</a></li>
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<li><a href="#">Billing System</a></li>
								<li><a href="#">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>
								<li><a href="#">Affillate Program</a></li>
								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Все права защищены © 2016 Тестовый интернет-магазин на базе Yii2.</p>
					<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
				</div>
			</div>
		</div>
		
	</footer><!--/Footer-->
        <!--Модальное окно корзины-->
        <?php Modal::begin([
            'header' => '<h2>Корзина</h2>',
            'id' => 'cart',
            'size' => 'modal-lg',
            'footer' => '<button type="button" class="btn btn-default" data-dismiss="modal">Продолжить покупки</button>
        <a href="' . Url::to(['cart/view']) . '" class="btn btn-success">Оформить заказ</a>
        <button type="button" class="btn btn-danger" onclick="clearCart()">Очистить корзину</button>'
        ]);
        
        
        Modal::end();
        ?>
        
<?php $this->endBody() ?><!--/Модальное окно корзины-->
<!--<script>
$(document).ready(function(){
    $("#search").keypress(function(e){
        //нажата клавиша enter
        if(e.keyCode==13){
         var action = $("#search").attr("action");
         var search = $("#search").attr("value");
         window.location.href = action + "/" + search;
//         $('#search').attr('action', '/search/' + q);
        }
    });

});
</script>-->
</body>
</html>
<?php $this->endPage() ?>