basic/models/Product.php
<?php


namespace app\models;
use yii\db\ActiveRecord;

class Product extends ActiveRecord {
    
    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }
    
    public static function tableName() {
        return 'product';
    }
    
    public function getCategory(){
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }
}

basic/controllers/CartController.php
<?php

namespace app\controllers;
use app\models\Product;
use app\models\Cart;
use app\models\Order;
use app\models\OrderItems;
use Yii;

class CartController extends AppController{
    //Добавление товара в корзину Ajax запросом
    public function actionAdd(){
        //получение id товара добавляемого в корзину
        $id = Yii::$app->request->get('id');
        //получение количества товара и приведение к целому числу
        $qty = (int)Yii::$app->request->get('qty');
        //Если qty не число, в корзину добавляется 1 товар,
        // иначе количество qty
        $qty = !$qty ? 1 : $qty;
        
        //запрос к БД
        $product = Product::findOne($id);
        //если запрос ничего не вернул
        if(empty($product)){
            return FALSE;
        }
        //откытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //модель
        $cart = new Cart();
        $cart->addToCart($product, $qty);
        
        //Добавление в корзину в случае отключения javascript
        if (!Yii::$app->request->isAjax){
            return $this->redirect(Yii::$app->request->referrer);
        }
        
        //отключение шаблона
        $this->layout = FALSE;
        
        return $this->render('cart-modal', compact('session'));
    }
    //Очистка корзины
    public function actionClear(){
        //открытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //удаление из сессии всех данных о товарах
        $session->remove('cart');
        $session->remove('cart.qty');
        $session->remove('cart.sum');
        
        //отключение шаблона
        $this->layout = FALSE;
        
        return $this->render('cart-modal', compact('session'));
    }
    
    //Удаление одного товара из корзины при нажатии на крестик
    public function actionDelItem(){
        //получение id товара удаляемого из корзины
        $id = Yii::$app->request->get('id');
        
        //открытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //Подключение модели
        $cart = new Cart();
        $cart->recalc($id);
        
        //отключение шаблона
        $this->layout = FALSE;
        
        return $this->render('cart-modal', compact('session'));
    }
    
    //Открытие корзины при нажатии на значек в Header
    public function actionShow(){
        
        //открытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //отключение шаблона
        $this->layout = FALSE;
        
        return $this->render('cart-modal', compact('session'));
    }
    //Обработка заказа
    public function actionView(){
        //открытие сессии
        $session = Yii::$app->session;
        $session->open();
        
        //Установка заголовка для страницы
        $this->setMeta('Корзина');
        
        //Подключение модели
        $order = new Order();
        
        if($order->load(Yii::$app->request->post())){
            $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];
            
            if($order->save()){
                $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success', 'Ваш заказ принят.');
                
                //отправка письма заказа
                Yii::$app->mailer->compose('order', ['session' => $session])
                        ->setFrom(['test@mail.ru' => 'shop2'])
                        ->setTo($order->email)
                        ->setSubject('Заказ')
                        ->send();
                
                //очистка корзины
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                        
                return $this->refresh();
            }else{
                Yii::$app->session->setFlash('error', 'Ошибка оформления заказа!');
            }
        }
        
        return $this->render('view', compact('session', 'order'));
    }
    
    //Сохранение заказанных товаров в таблицу order_items
    protected function saveOrderItems($items, $order_id){
        foreach($items as $id => $item){
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty'] * $item['price'];
            $order_items->save();
        }
    }
}

basic/controllers/CategoryController.php
<?php

namespace app\controllers;
use app\models\Category;
use app\models\Product;
use yii\data\Pagination;
use yii\web\HttpException;
use Yii;

class CategoryController extends AppController {
    
    public function actionIndex(){
        //Запрос к БД для Популярные товары
        $hits = Product::find()->where(['hit' => '1'])->limit(9)->all();
        $this->setMeta('Тестовый магазин на Yii2');
        return $this->render('index', compact('hits'));
    }
    
    public function actionView($id){
//        $id = Yii::$app->request->get('id');
        //Запрос на категорию по id
        $category = Category::findOne($id);
        //В случае, если такой категории нет выводится страница с ошибкой
        if(empty($category)){
            throw new HttpException(404, 'Что-то пошло не так и мы не смогли найти нужную категорию');
        }
        
//        $products = Product::find()->where(['category_id' => $id])->all();
        //Включение пагинации для товаров по категориям
        $query = Product::find()->where(['category_id' => $id]);
        $pages = new Pagination(['totalCount' => $query->count(),
            'pageSize' => 3, 'forcePageParam' => FALSE, 'pageSizeParam' => FALSE]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        
        //Установка метатегов
        $this->setMeta('Тестовый магазин на Yii2 | ' . $category->name, $category->keywords,
                $category->description);
        
        return $this->render('view', compact('products', 'pages', 'category'));
    }
    
    public function actionSearch(){
        //получение поискового запроса с учетом пробелов
        $q = trim(Yii::$app->request->get('q'));
        
        //Установка метатегов
        $this->setMeta('Тестовый магазин на Yii2 | Поиск: ' . $q);
        
        //обработка поиска в случае, если строка поиска пустая
        if(!$q){
            return $this->render('search');
        }
        //Включение пагинации для товаров по категориям из поискового запроса
        $query = Product::find()->where(['like', 'name', $q]);
        
        $pages = new Pagination(['totalCount' => $query->count(),
            'pageSize' => 3, 'forcePageParam' => FALSE, 'pageSizeParam' => FALSE]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        
        return $this->render('search', compact('products', 'pages', 'q'));
    }
}

basic/controllers/ProductController.php
<?php

namespace app\controllers;
use app\models\Category;
use app\models\Product;
use Yii;
use yii\web\HttpException;

class ProductController extends AppController {
    
    public function actionView($id){
        //Получение id товара через Get запрос
//        $id = Yii::$app->request->get('id');
        //Ленивая загрузка данных товара по id из БД
        $product =  Product::findOne($id);
        //В случае, если такого товара нет, выводится страница с ошибкой
        if(empty($product)){
            throw new HttpException(404, 'Что-то пошло не так и страница с товаром не была найдена');
        }
        
        //Жадная загрузка
//        $product = Product::find()->with('category')->where(['id' => $id])->limit(1)->one();
        //Запрос к БД для Популярные товары
        $hits = Product::find()->where(['hit' => '1'])->limit(9)->all();
        //Установка метатегов
        $this->setMeta('Тестовый магазин на Yii2 | ' . $product->name, $product->keywords,
                $product->description);
        
        return $this->render('view', compact('product', 'hits'));
    }
}

basic/views/product/view.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>
<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Категории</h2>
						<ul class="catalog category-products"><!--Левое меню категорий-->
                                                <?= \app\components\MenuWidget::Widget(['tpl' => 'menu']); ?>
                                                </ul><!--/Левое меню категорий-->
					</div>
				</div>
<?php 
$mainImage = $product->getImage(); 
$gallery = $product->getImages();
?>
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
<!--								<img src="/images/product-details/1.jpg" alt="" />-->
                                                                <?= Html::img($mainImage->getUrl(), ['alt' => $product->name]) ?>
<!--								<h3>ZOOM</h3>-->
							</div>
                                                    
							<div id="similar-product" class="carousel slide" data-ride="carousel">
                                                            <div class="carousel-inner"><!--Wrapper for slides -->
                                                                <?php $count = count($gallery); $i = 0; foreach ($gallery as $img): ?>
                                                                <?php if($i % 3 == 0): ?>
                                                                <div class="item <?php if ($i == 0){echo ' active';}?>">
                                                                <?php endif; ?>
                                                                      <a href="">
                                                                          <?= Html::img($img->getUrl('84x85'), ['alt' => $product->name]) ?>
                                                                      </a>
                                                                <?php $i++; if($i % 3 == 0 || $i == $count): ?>
                                                                    </div>
                                                                <?php endif; ?>
                                                                <?php endforeach; ?>
                                                            </div><!--Wrapper for slides -->

                                                                            <!--Controls -->
								  <a class="left item-control" href="#similar-product" data-slide="prev">
									<i class="fa fa-angle-left"></i>
								  </a>
								  <a class="right item-control" href="#similar-product" data-slide="next">
									<i class="fa fa-angle-right"></i>
								  </a>
							</div>

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
<!--								<img src="/images/product-details/new.jpg" class="newarrival" alt="" />-->
                                                                <?php if($product->new): ?>
                                                                    <?= Html::img("@web/images/home/new.png", ['alt' => 'Новинка', 'class' => 'new']); ?>
                                                                    <?php endif; ?>
                                                                    <?php if($product->sale): ?>
                                                                    <?= Html::img("@web/images/home/sale.png", ['alt' => 'Распродажа', 'class' => 'new']); ?>
                                                                <?php endif; ?>
                                                            
								<h2><?= $product->name ?></h2>
								<p>Web ID: 1089772</p>
								<img src="/images/product-details/rating.png" alt="" />
								<span>
									<span>&#8381;<?= $product->price ?></span>
									<label>Количество:</label>
									<input type="text" value="1" id="qty" />
                                                                        
                                                                        <a href="<?= Url::to(['cart/add', 'id' => $product->id]) ?>"
                                                                           data-id="<?= $product->id ?>"
                                                                           class="btn btn-fefault cart add-to-cart">
										<i class="fa fa-shopping-cart"></i>
										В корзину
									</a>
								</span>
<!--								<p><b>Availability:</b> In Stock</p>
								<p><b>Condition:</b> New</p>-->
                                                                <p><b>Категория:</b> <a href="<?= Url::to(['category/view', 'id' => $product->category->id])?>"><?= $product->category->name ?></a></p>
                                                                
                                                                
							</div><!--/product-information-->
						</div>
					</div><!--/product-details-->
                                        
                                        <div><!--Вывод описания товара-->
                                            <h2>Описание:</h2>
                                             <?= $product->content ?>
               
                                        </div><!--/Вывод описания товара-->
                                        <br>
                                        
					
					<div class="recommended_items"><!--features_items-->
						<h2 class="title text-center">Популярные товары</h2>
						
						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
                                                            <?php $count = count($hits); $i = 0; foreach ($hits as $hit): ?>
								<?php if($i % 3 == 0): ?>
                                                                <div class="item <?php if($i == 0){echo 'active';} ?>">
                                                                <?php endif; ?>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
                                                                                                    <a href="<?= Url::to(['product/view', 'id' => $hit->id]) ?>">
                                                                                                        <?php $mainImage = $hit->getImage();?>
                                                                                                        <?= Html::img($mainImage->getUrl(), ['alt' => $hit->name]); ?>
                                                                                                    </a>
													<h2>&#8381;<?= $hit->price?></h2>
                                                                                                    <a href="<?= Url::to(['product/view', 'id' => $hit->id]) ?>">
													<p><?= $hit->name ?></p>
                                                                                                    </a>
                                                                                                        <a href="<?= Url::to(['cart/add', 'id' => $hit->id]) ?>"
                                                                                                           data-id="<?= $hit->id ?>"
                                                                                                           class="btn btn-fefault cart add-to-cart">
                                                                                                                <i class="fa fa-shopping-cart"></i>
                                                                                                                В корзину
                                                                                                        </a>
<!--													<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</button>-->
												</div>
											</div>
										</div>
									</div>
                                                                <?php $i++; if($i % 3 == 0 || $i == $count): ?>
								</div>
                                                                <?php endif; ?>
                                                            <?php endforeach; ?>
							</div>
							 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
								<i class="fa fa-angle-left"></i>
							  </a>
							  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
								<i class="fa fa-angle-right"></i>
							  </a>			
						</div>
					</div><!--/features_items-->
					
				</div>
			</div>
		</div>
	</section>